<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cheers [
<!ELEMENT execution (radius,length)>
<!ELEMENT radius (#PCDATA)>
<!ELEMENT length (#PCDATA)>
]>
<cheers>
<execution><radius>1</radius><length>1.1920544934009658</length></execution><execution><radius>14</radius><length>16.688762907613523</length></execution><execution><radius>12.2</radius><length>14.543064819491782</length></execution><execution><radius>10.456</radius><length>12.464121783000499</length></execution><execution><radius>12</radius><length>14.304653920811589</length></execution><execution><radius>13</radius><length>15.496708414212556</length></execution><execution><radius>15.5</radius><length>18.47684464771497</length></execution><execution><radius>1</radius><length>1.1920544934009658</length></execution><execution><radius>22.2</radius><length>26.46360975350144</length></execution></cheers>